ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "chapter_negative_marking" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Subject" ADD COLUMN IF NOT EXISTS "chapter_wrong_penalty" DOUBLE PRECISION NOT NULL DEFAULT 0.25;

ALTER TABLE "Test" ADD COLUMN IF NOT EXISTS "wrong_penalty" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "TestAttempt" ALTER COLUMN "score" TYPE DOUBLE PRECISION;
